name: Python CI and PR

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install pytest

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest test_app.py || echo "No tests found, skipping"

  update_dev_branch:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure Dev Branch is Up to Date
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin dev || echo "No remote updates"
          git push origin dev || echo "No changes to push"

  create_pr:
    needs: update_dev_branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated PR from dev to main"
          title: "Automated PR from dev to main"
          body: |
            Automated Pull Request created by GitHub Actions.
            This PR merges the latest changes from dev to main.
          base: main
          branch: dev
