name: Python CI

on: 
  push:
    branches:
      - dev  # Only trigger workflow when changes are pushed to 'dev'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install pytest

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest test_app.py

  merge_to_main:
    needs: test  # This job only runs if tests pass
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Merge Dev to Main
        run: |
          git fetch origin
          git checkout main
          git merge --ff-only dev
          git push origin main
