name: Python CI

on: 
  push:
    branches:
      - dev  # Only trigger workflow when changes are pushed to 'dev'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install pytest

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest test_app.py
